name: NestJS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Clona el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Instala Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Cambia a la versión de Node.js que usas

      # Instala dependencias
      - name: Install dependencies
        run: npm install

      # Compila el proyecto
      - name: Build project
        run: npm run build

      # Opcional: Despliega (ejemplo: en Vercel)
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel deploy --prod --token $VERCEL_TOKEN
