# Flujo de trabajo simple para implementar contenido estático en Github Pages
name: CI API TOGETHER

on:
  # Se ejecuta en anotaciones dirigidas a la rama predeterminada
  push:
    branches: ['main']

  # Te permite ejecutar este flujo de trabajo manualmente desde la pestaña Acciones
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        # cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
